fix(android): remove sheetRootView from parent during dialog cleanup
Fixes crash on second sheet presentation caused by sheetRootView
still having a parent reference from the previous dialog.

When cleanupDialog() is called after dismiss, we now properly
removeView(sheetRootView) from the container to allow it to be
re-attached to the new dialog instance on the next presentation.

Error was:
java.lang.IllegalStateException: The specified child already has
a parent. You must call removeView() on the child's parent first.